# Site settings
title: Nathen Byford - Statistician & Data Scientist
email: nate@natebyford.com
description: >-
  Transforming complex data into actionable insights through advanced statistical analysis, 
  machine learning, and data visualization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.natebyford.com" # the base hostname & protocol for your site
github_username: nathenbyford
linkedin_username: nathen-byford

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nathen Byford"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md