project:
  type: website

website:
  title: "Nate Byford"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - text: "Projects"
        menu: 
          - current_projects.qmd
          - past_projects.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "About"
        file: about.qmd
    right:
    - icon: github
      href: https://github.com/nathenbyford
      aria-label: GitHub
    - icon: linkedin
      href: https://www.linkedin.com/in/nathen-byford/
      aria-label: LinkedIn

format:
  html:
    theme: 
      light: yeti
      dark: [yeti, theme-dark.scss]
    css: styles.css
    toc: true
    mainfont: sans-serif

execute: 
  freeze: auto
