project:
  type: website

website:
  title: "Nate Byford"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - text: "Projects"
        file: current_projects.qmd
      - about.qmd
      - text: "Notes"
        file: theory-notes.qmd
    right:
    - icon: github
      href: https://github.com/nathenbyford
      aria-label: GitHub
    - icon: linkedin
      href: https://www.linkedin.com/in/nathen-byford/
      aria-label: LinkedIn

format:
  html:
    theme: 
      light: yeti
      dark: yeti-dark
    css: styles.css
    toc: true
    mainfont: sans-serif

execute: 
  freeze: auto
