---
title: "Theory of Statistics notes"
author: "Nathen Byford"
format: 
  html: 
    mainfont: "sans-serif"
    toc: true
---

All notes come from reading Casella and Berger, and slides from STA 5381 and STA 5382.

# Probability Theory
> "The theory of probability is the only mathematical tool available to help map the unknown and the uncontrollable." - Ronald A. Fisher

Probability forms the foundation of statistics that all analysis is firmly built upon. At its core, probability provides a framework to understand and quantify uncertainty. By assigning numerical values to uncertain events, it enables statisticians to model and analyze various phenomena with precision and rigor. Probability theory allows us to determine the likelihood of different outcomes, evaluate the chances of events occurring, and measure the degree of confidence in our conclusions. Whether it is estimating population parameters, testing hypotheses, or making predictions, statistics relies heavily on probability to make sense of the inherent variability and randomness present in data. Through the language of probability, statisticians can navigate the intricate landscape of uncertainty and draw meaningful insights that shape our understanding of the world.


## Set Theory
If probability is the foundation of statistics, then set theory is the cornerstone of probability. It is important to have a basic understanding of set theory to understand probability and statistics.

**Sample Space:** The set $\mathcal{S}$ of all possible outcomes of an experiment is called the *sample space* for the experiment. *Other possible notations of the sample space are* $\{\Omega \text{ or } \mathcal{X}\}$. 

Since the sample space contains all possible values of a given experiment we need to recognize the two types of sample spaces: *countable* and *uncountable*. A countable sample space is one that we can count all the possible outcomes either values or specific outcomes, these tend to have specific set of possible outcomes or an integer value. Uncountable sample spaces have infinitely many possible outcomes, an example of this would be the sample space $\mathcal{S} \in (0, \infty)$.

**Event:** Any collection of possible outcomes, that is any partition of the set $\mathcal{S}$. This includes the total partition of the entire set $\mathcal{S} \in \mathcal{S}$.

There are two types of events, *simple events* and *complex events*.

* **Simple events**: An event with a single outcome, a simple event can only happen one way.
* **Complex events**: The combination of two or more simple events. The number if ways a complex event can occur is determined by counting techniques.

**Set Operations**
Let $A$ be a set from the sample space $\mathcal{S}$ and $B$ be another set from the sample space $\mathcal{S}$.

* Union:
$$A \cup B = \left\{\omega \in \mathcal{S}: \omega \in A ~{} \mathbf{or} ~{} \omega \in B\right\}$$
* Intersection:
$$A \cap B = \left\{\omega \in \mathcal{S}: \omega \in A ~{} \mathbf{and} ~{} \omega \in B\right\}$$
* Compliment:
$$A^{c} = A^{\prime} = \left\{\omega \in \mathbf{S}: \omega \notin A\right\}$$

When two sets share nothing between the two, then $A \cap B = \emptyset$. Where $\emptyset$ is called the *null or empty set*, the set that contains nothing.

### Properties of set operators

* Commutativity: 
$$A \cup B = B \cup A$$
$$A \cap B = B \cap A$$
* Associativity:
$$A \cup (B \cup C) = (A \cup B) \cup C$$
$$A \cap (B \cap C) = (A \cap B) \cap C$$
* Distributive:
$$A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$$
$$A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$$
* DeMorgan's Law:
$$(A \cup B)^{c} = A^{c} \cap B^{c}$$
$$(A \cap B)^{c} = A^{c} \cup B^{c}$$
Note: Using a Venn diagram to show these properties does not count as mathematical proof and a proof can be found using the subsets and showing they are equal from both sides.

Both unions and intersections can be expanded to infinite sets.
$$\cup_{i = 1}^{\infty} A_i = \left\{\omega \in \mathcal{S}: \omega \in A_i \text{ For some } i\right\}$$
$$\cap_{i = 1}^{\infty} A_i = \left\{\omega \in \mathcal{S}: \omega \in A_i \text{ For all } i\right\}$$
Two events $A$ and $B$ are said to be *disjoint* if $A \cap B = \emptyset$. The events $A_1, A_2, \ldots$ are said to be pairwise disjoint if $A_i \cap A_j = \emptyset$ for all $i \ne j$.

Disjoint sets are sets with no points in common.

If $A_1, A_2, \ldots$ are pairwise disjoint and $\cup_{i=1}^{\infty}A_i = S$, then the collection $A_1, A_2, \ldots$ is a *partition* of $S$.

## Basics of probability theory

> "The theory of probability is founded on the assumption that it is possible to associate a numerical measure with the likelihood of each event." - Andrey Kolmogorov

When an experiment is performed, the result is an outcome $\omega$ in the sample space $\mathcal{S}$. The probability of any outcome $\omega \in \mathcal{S}$ is the limit of the relative frequency of the event, $\omega$,  as the number of times the experiment is performed goes to infinity.

### Sigma algebras ($\sigma$-algebra)
A sigma algebra or Borel field is the set of all possible outcomes of an experiment. The requirements for a $\sigma$-algebra/Borel field($\mathcal{B}$) are

* $\emptyset \in \mathcal{B}$ (The null set is contained within the $\sigma$-algebra)
* If $A \in \mathcal{B}$, then $A^{c} \in \mathcal{B}$ also. (Closed under complementation)
* If $A_1, A_2, \ldots \in \mathcal{B}$, then $\cup_{i=1}^{\infty} A_i \in \mathcal{B}$ (Closed under countable unions)

The smallest possible $\sigma$-algebra is called the trivial set and contains the sample space $\mathcal{S}$ and the null set $\emptyset$.

We tend not to be interested in the trivial set, we are more interested in the smallest set that isn't the trivial set. The *power set*($\mathcal{P_S}$) is the next smallest $\sigma$-algebra, this is the set of all the subsets within $\mathcal{S}$ and $\emptyset$.
The cardinality or size of the power set is:
$$\mathcal{C(P_S)} = 2^{\mathcal{C(S)}}$$

### Axioms of probability
Given a sample space $\mathcal{S}$ and an associated $\sigma$-algebra $\mathcal{B}$, a probability function is a function $P$ with domain $\mathcal{B}$ that satisfies:

1. $P(A) \ge 0, ~{} \text{ for all } ~{} A \in {\mathcal{B}}$
2. $P(S) = 1$
3. If $A_1, A_2, ...$ are pairwise disjoint, then $P \left(\cup_{i=1}^\infty A_i \right) = \Sigma_{i=1}^\infty P(A_i)$

These are the *axioms of probability* or Kolmogorov's axioms.

There are some people who disagree with the third axiom, the axiom of countable additivity. Specifically a school of statistics led by deFinetti, who has decided to replace it with the axiom of finite additivity.

That is, if $A \in \mathcal{B}$ and $B \in \mathcal{B}$ are disjoint, then
$$P(A \cup B) = P(A) + P(B)$$
Although the axiom of finite additivity is easier to prove or see, it brings with it some unexpected consequences that the axiom of countable additivity does not introduce. Therefore, it is better to use the first set of axioms (Kolmogorov's axioms).

**Probability space**

A probability space can be represented by the probability triple denoted as $(\mathcal{S}, \mathcal{B}, P)$, where $\mathcal{S}$ is the sample space, $\mathcal{B}$ is a Borel field of $\mathcal{S}$, and $P$ is a valid probability statement.

Let $\mathcal{S} = \{ \omega_1, \ldots, \omega_n \}$ be a finite set and $\mathcal{B}$ be any $\sigma$-algebra of $\mathcal{S}$. Let $p_1, \ldots, p_n$ be non-negative real numbers that sum to 1. For any $A \in \mathcal{B}$ define $P(A)$ by
$$P(A) = \sum_{\{i: s_i \in A\}} p_i$$

### Calculus of Probabilities
If $P$ is a valid probability function and $A$ is any set in $\mathcal{B}$

a) $P(\emptyset) = 0$, where $\emptyset$ is the null set;
a) $P(A) \le 1$;
a) $P(A^{c}) = 1 - P(A)$.

**Probability of sets and set operations**
\begin{align*}
  P(A \cup B) &= P(A) + P(B) \\
	P(A \cap B^c) &= P(A) - P(A \cap B) \\
	P(A \cup B) &= P(A) +P(B) - P(A \cap B) \\
	\text{If } A &\subset B \text{ then } P(A) \le P(B)
\end{align*}
**Bonferoni's inequality**
$$P(A \cap B) \ge P(A) + P(B) - 1$$

**Law of total probability**
$$P(A) = \Sigma_{i = 1}^\infty P(A \cap C_i)$$
For $C_1, C_2, ... \in {\mathcal{B}}$, where $C_1, C_2, ...$ are a partition of $\mathcal{S}$. This will come in use a bit later when we use Bayes theorem and conditionals.

**Boole's Inequality**
$$ P(\cup_{i = 1}^\infty A_i) \le \Sigma P(A_i)$$ 
For any collection of sets, $A_1, A_2, \ldots \in {\mathcal{B}}$

## Counting Techniques and Enumerating Outcomes
**Fundamental Theorem of Counting:** If a job consists of $k$ separate tasks, the $i$-th of which can be done in $n_i$ ways. $i = 1, 2, ..., k$, then the entire job can be done in $n_1 \times n_2 \times ... \times n_k$ ways.

* **What is a "job"?**
A "job" is what produces of the final set, examples include tossing a coin $n$ times, tossing two dice one at a time. Basically the "job" is the experiment.
* **What is a "task"?**
A "task" is the action being done over and over for the job, examples include, flipping a coin, rolling a die, etc. 

There are two properties of the experiment that must be known to determine the size of the sample space.

* *Sampling Scheme:* with or without replacement
* *Outcomes:* ordered or unordered.

**Sampling Schemes**

* without replacement
  + Once a unit is selected for the sample it is removed from the population, can't be sampled again.
  + **Cannot** have repeat units in the outcome.
* With replacement
  + When a unit is selected for the sample it is placed back into the population, can be sampled again.
  + **Can** have repeat units in the outcome.
  
**Outcome**

* Ordered outcomes
  + When an experiment involves two or more tasks, if the same results have a different ordering it is a **different** outcome.
* Unordered outcomes
  + When an experiment involves two or more tasks, if the same results have a different ordering it is the **same** outcome, **does not** create a new outcome.
  
### Counting Techniques
**Ordered without Replacement**

If a population with $n$ units has $r$ units selected without replacement. If the outcomes are ordered, the the number of outcomes is 
\begin{equation*}
  \mathcal{C(S)} = \frac{n!}{(n - r)!}
\end{equation*}

**Ordered with Replacement**

If a population with $n$ units has $r$ units selected with replacement. If the outcomes are ordered, the the number of outcomes is 
\begin{equation*}
  \mathcal{C(S)} = n^r
\end{equation*}

**Unordered without Replacement**

If a population with $n$ units has $r$ units selected without replacement. If the outcomes are unordered, the the number of outcomes is 
\begin{equation*}
  \mathcal{C(S)} = \binom{n}{r} = \frac{n!}{(n - r)! r!}
\end{equation*}
This notation is called choose, here it would be said "There are $n$ choose $r$ possible outcomes."

**Unordered with Replacement**

If a population with $n$ units has $r$ units selected with replacement. If the outcomes are unordered, the the number of outcomes is 
\begin{equation*}
  \mathcal{C(S)} = \binom{n + r - 1}{r} = \frac{(n + r - 1)!}{(n - 1)! r!}
\end{equation*}

### Enumerating outcomes
To apply the counting techniques to compute probabilities enumerate the outcomes and then divide by the cardinality of the sample space.
$$ P(A) = \frac{{\cal{C}}(A)}{{\cal{C}(S)}}  = \frac{{\cal{C}}(A)}{N} $$
Ways to enumerate the outcomes:

* Count up the amount of possibilities (Simple examples only).
* Use counting techniques to determine $\mathcal{C}(A)$.

In some cases the sample may need to be split into more than one event to use counting techniques. If so we would use the Fundamental Theorem of Counting to get the total number of outcomes.

## Conditional Probability, Independence,  Random Variables, and Distribution Functions
Consider the sample space $\cal{S}$ and $\cal{B}$ a $\sigma$-algebra of the sets in $\cal{S}$. Let $A$ and $B$ be any two events in $\cal{B}$ with $P(B) > 0$. Then the *conditional probability* of $A$ given $B$ (has occurred), is written as $P(A|B)$ is 
$$ P(A|B) = \frac{P(AB)}{P(B)} $$
**Bayes Rule**

From the expression for conditional probability we can derive the following.
\begin{align*}
  P(A|B) &= \frac{P(A \cap B)}{P(B)} \\
  \Rightarrow P(A \cap B) &= P(A|B)P(B) \\
  \Rightarrow P(B \cap A) &= P(B|A)P(A) \\
  \Rightarrow P(A|B) &= \frac{P(B|A)P(A)}{P(B)}
\end{align*}
Consider a sample space $\cal{S}$ and a Borel field $\cal{B}$ of the sets in $\cal{S}$. Let $A_1, A_2, ... \in \cal{B}$ be a partition of $\cal{S}$ and $B \in \cal{B}$ another set with $P(B) > 0$. Then for each $i = 1, 2, ...$
$$P(A_i|B) = \frac{P(B|A_i)P(A_i)}{\Sigma_{j=1}^\infty P(B|A_j)P(A_j)}$$

The denominator comes from the law of total probability.

Possibly the single most important property in statistics, *independence*. 

Let $\cal{S}$ be a sample space, and $\cal{B}$ a Borel field of the sets in $\cal{S}$. Let $A$ and $B$ be any two events in $\cal{B}$ such that $P(A)>0$ and $P(B)>0$. The events $A$ and $B$ are said to be *statistically independent* (or independent) if 
\begin{align*}
  P(AB) &= P(A)P(B), \text{ or} \\
  P(A|B) = P(A) &\text{ or } P(B|A) = P(B)
\end{align*}
If $A$ and $B$ are not independent, then they are dependent events. Another way to think of independence in terms of conditional probability is: if knowing that one event has occurred does not change the probability that the other event will occur.

**Mutually Exclusive Events**

Let $\mathcal{S}$ be a sample space, and $\mathcal{B}$ a $\sigma$-algebra on the sets in $\cal{S}$. Let $A$ and $B$ be any two mutually exclusive events in $\mathcal{B}$ with $P(A)>0$ and $P(B)>0$. Then $A$ and $B$ are statistically dependent events.

**Independence of Complements**

If $A$ and $B$ are independent events, then the following pairs are also independent.

* $A$ and $B^c$
* $A^c$ and $B$
* $A^c$ and $B^c$

**Independence of Multiple Events**

Also called \textit{Mutually independent events}: A collection of events $A_1, A_2, ... , A_n$ are mutually independent if for any sub collection $A_{i1}, ..., A_{ik}$ we have 
$$ P\left(\bigcap_{j=1}^k A_{ij}\right) = \prod_{j=1}^k P(A_{ij}) $$

**Random Variables**

Most experiments are easily described using a summary variable instead of the original probability structure.

A *random variable* is a function from the sample space $\cal{S}$ into the real numbers.

* The domain of $A$ is $\cal{S}$. Therefore, for each $\omega_i \in \cal{S}$, we have $X(\omega_i) = x_i$, where $x_i \in$ real numbers.
* The range of $X(\omega)$ is all real numbers, or a subset of all real numbers.

**Induced Probability Function**

Consider a finite sample space $\cal{S} = \{\omega_1, \omega_2, ... , \omega_n\}$ with probability function $P$. Define the random variable $X({\cal{S}}) \rightarrow {\cal{X}}$ where ${\cal{X}} = \{x_1, x_2, ..., x_n\}$. The induced probability function $P_X$ is
$$P_X(X = x_i) = P(\{\omega_j \in {\cal{S}} : X(\omega_j) = x_i\} $$

**Distribution Functions**

Every random variable has associated with it a distribution function called the cumulative distribution function (CDF).

The CDF of a random variable $X$ is denoted by $F_X(x)$, and is defined as
$$ F_X(x) = P_X(X \le x), \text{ for all } x \in {\cal{X}} $$
Right continuous function:
$$\lim_{x \rightarrow x_0^+} f(x)= f(x_0)$$
Properties of a CDF:

* $\lim_{x \rightarrow -\infty} F_X(x) = 0$ and $\lim_{x \rightarrow \infty} F_X(x) = 1$
* $F_X(x)$ is a non-decreasing function of $x$
* $F_X(x)$ is a right-continuous function

**Continuous Random Variables**

A random variable $X$ is defined to be continuous if $F_X(x)$ is a continuous function of $x$. 

**Discrete Random Variables**

A random variable $X$ is said to be discrete if $F_X(x)$ is a step function of $x$.

**Identically Distributed**

If $X$ and $Y$ have CDFs $F_X$ and $F_Y$ and are identically distributed, then
$$ F_X(x) = F_Y(x) \text{ for all } x$$

# Transformations and Expectations

## Transformations
Transformations take a set and map it onto a new sample space and return a new set.

* Let $X$ be a random variable with CDF $F_X(x)$ and $Y = g(X)$ be a function of $X$.
* Since $X$ is a random variable, then $Y = g(X)$ is a random variable. Therefore for a given set $A$
$$ P(Y \in A) = P(g(X) \in A)$$
* The distribution of $Y$ will depend on $g$ and on $F_X(x)$.
* $g$ defines a mapping from $\cal{X}$ to a new sample space, which we denote as $\cal{Y}$
* The inverse mapping of $g(X) = G^{-1}(Y)$:
$$ g^{-1}(A) = \{x \in {\cal{X}}: g(x) \in A\} $$

### Monotone Transformations
The easiest transforms are when $g$ is monotone.

Properties of a *monotone function*:

* One-to-one: each value $x$ goes to only one $y$, and each value of $y$ comes from at most one value $x$.
* onto: For each $y \in {\cal{Y}}$, here is an $x \in {\cal{X}}$ such that $g(x) = y$.

Steps for monotone transform:

* Define $\cal{X}$ and $\cal{Y}$.
\begin{align*}
  {\cal{X}} &= \{x : f_X(x) > 0 \} \\
  {\cal{Y}} &= \{y : y = g(x) \text{ for some } x \in {\cal{X}} \}
\end{align*}
* If $g$ is an increasing monotone function of $\cal{X}$, 
$$ F_Y(y) = F_X(g^{-1}(y)) \text{ for } y \in {\cal{Y}} $$
* If $g$ is a decreasing function on ${\cal{X}}$ and $X$ is a continuous random variable, 
$$ F_Y(y) = 1 - F_X\left(g^{-1}(y)\right) \text{ for } y \in \cal{Y} $$

The PDF of a monotone transform will be
\begin{equation}
  f_Y(y) = f_X(g^{-1}(y))\left|\frac{d}{dy} g^{-1}(y)\right|
\end{equation}

### Non-monotone transformation
A non-monotone function will need to be split up into separate functions $g_i(x)$ at the points of the partition $A_1, A_2, .., A_k$ of $\cal{X}$ such that $P(X \in A_0) = 0$.

* Each $g_i(x)$ is monotone on $A_i$
* The set ${\cal{Y}} = \{y: y = g_i(x)\}$ for some $x \in A_i$ for each $i = 1, 2, ..., k$
* $g^{-1}(y)$ has a continuous derivative on $\cal{Y}$ for rach $i = 1, 2, ..., k$. Then 
\begin{equation}
  f_Y(y) = \sum_{i=1}^k f_X(g^{-1}(y)) \left| \frac{d}{dy} g^{-1}(y) \right|
\end{equation}

**Probability Integral Transform**
Let $X$ have a continuous CDF $F_X(x)$ and define the random variable $Y$ as $Y = F_X(X)$. Then $Y$ is uniformly distributed on $(0, 1)$; that is , $P(Y \le y) = y$ for $ 0 < y < 1$.

## Expectations

The *expected value* of a random variable $X$ is denoted by $E[X]$. The expected value is a weighted average of the values of $X$, where the weights are the assigned from the PMF or PDF.

* If $X$ is discrete with PMF $f_X(x)$, then 
$$ E[X] = \sum x f_X(x) $$
* If $X$ is continuous with PDF $f_X(x)$, then
$$ E[X] = \int x f_X(x) dx $$

We can also take the expected value of transformations or functions of the data:

* If $X$ is discrete with PMF $f_X(x)$, then
$$ E[g(x)] = \sum g(x) f_X(x) $$
* If $X$ is continuous with PDF $f_X(x)$, then
$$ E[X] = \int g(x) f_X(x) dx $$

**Properties of expectations:**

Let $X$ be a random variable and let $a$, $b$, and $c$ be real constants. Then for any functions $g_1(x)$ and $g_2(x)$ whose expectation exist

* $E[ag_1(X) + bg_2(X) + c] = aE[g_i(X)] + bE[g_2(X)] + c$
* If $g_1(x) \ge 0$ for all $x$, then $E[g_1(x)] \ge 0$
* If $g_1(x) \ge g_2(x)$ for all $x$, then $E[g_1(x)] \ge E[g_2(x)]$ 
* If $a \le g_1(x) \le b$ for all $x$, then $a \le E[g_1(X)] \le b$

### Moments
For each integer $n$, the $n$-th moment of $X$, denoted $\mu_n^\prime$, is defined as
$$ \mu_n^\prime = E[X^n] $$
The $n$-th central moment of $X$, denoted $\mu_n$, is defined as
$$ \mu_n = E[(X - \mu)^n] $$
Note on the two most important moments:

The two most important moments are the 1st moment and the second central moment, called the *mean* and *variance* respectively.
\begin{align*}
  \mu &= E[X] \\
  \text{Var}(X) &= E[(X - E[X])^2] \\
  &\text{or} \\
  \text{Var}(X) &= E[X^2] - (E[X])^2
\end{align*}

# Common families of Distributions

## Discrete Distributions
Expected value is defined as: $E[X] = \sum_{i=1}^{n} X f_X(x)$

:::: {.columns}

::: {.column width="50%"}
| Bernoulli($p$)
|   PMF:$f(x|p) = p^x(1-p)$ 
|   Mean: $\mu = p$ 
|   Variance: $\sigma^2 = p(1-p)$

| Binomial($n, p$)
|   PMF:$f(x| n, p) = \binom{n}{x} p^x {(1-p)}^{n-x}$ 
|   Mean: $\mu = \text{E}[X] = np$ 
|   variance: $\sigma^2 = \text{Var}[X] = np(1-p)$

| Geometric($p$)
|   PMF: $f(x|p) = p{(1-p)}^{x-1}$
|   CDF: $F(X) = 1 - {(1-p)}^x$
|   Mean: $\mu = \frac{1}{p}$
|   $\sigma^2 = \frac{1-p}{p^2}$
:::

::: {.column width="50%"}
| Poisson($\lambda$)
|   PMF: $f(x|\lambda) = \frac{\lambda^{x}e^{-\lambda}}{x!}$
|   Mean: $\mu = \lambda$
|   $\sigma^2 = \lambda$

| Negative Binomial($r, p$)
|   PMF: $f(x|r, p) = \binom{r + x + 1}{x} p^r (1-p)^x$
|   Mean: $\mu = \frac{r(1-p)}{p}$
|   $\sigma^2 = \frac{r(1-p)}{p^2}$

| Hypergeometric($N, M, K$)
|   PMF: $f(x|N, M, K) = \frac{\binom{M}{x}\binom{N-M}{K-x}}{\binom{N}{K}}$
|   Mean: $\mu = \frac{KM}{N}$
|   $\sigma^2 = \frac{KM}{N}\frac{(N-M)(N-K)}{N(N-1)}$
:::

::::

## Continuous Distributions
The expected value of a coninuous distribution is, $\text{E}[X] = \int_{x \in {\mathcal{A}}} x f(X) dx$

::::{.columns}

:::{.column width="50%"}
| Uniform($a, b$)
|   $f(x|a, b) = \frac{1}{b - a}$
|   $\mu = (a + b) / 2$
|   $\sigma^2 = (b - a)^2 / 12$

| exponential($\lambda$)
|   $f(x|\lambda) = \frac{1}{\lambda} e^{- x / \lambda}$
|   $F(x|\lambda) = 1 - e^{-x / \lambda}$
|   $\mu = \lambda$
|   $\sigma^2 = \lambda^2$

| Normal($\mu, \sigma^2$)
|   $f(x| \mu, \sigma^2) = \frac{1}{\sqrt{2 \pi \sigma^2}} \exp\{-\frac{x - \mu}{2 \sigma^2}\}$
|   $\mu = \mu$
|   $\sigma^2 = \sigma^2$
:::

:::{.column width="50%"}
| Gamma($\alpha, \beta$)
|   $f(x|\alpha, \beta) = \frac{1}{\Gamma(\alpha)\beta^{\alpha}} x^{\alpha - 1} \exp{-x / \beta}$
|   $\mu = \alpha \beta$
|   $\sigma^2 = \alpha \beta^2$

| Beta($\alpha, \beta$)
|   $f(x| \alpha, \beta) = \frac{1}{\beta(\alpha, \beta)} x^{\alpha - 1} {(1-x)}^{\beta-1}$
|   $\mu = \alpha / (\alpha + \beta)$
|   $\sigma^2 = (\alpha \beta) / \{(\alpha + \beta)^2(\alpha + \beta + 1)\}$
:::


::::